### ISSUE TITLE
Move the legend somewhere "not in the middle"

### ISSUE THREAD

**Issue by bkleeman** [RDCEP/energy-maps#18]
Narrow the width if possible. Needs scaling info eventually.

Tentative design suggestion: "Alignment-wise, I'd make the padding on the legend match the margin between the third and fourth column in the header, then align the right edge of third column in the header with the outer edge of the legend frame, and the left edge of the fouth column with the edge of the legend's content. If that makes any sense."

Similar to this:
![image](https://user-images.githubusercontent.com/20052075/91772220-0d665780-ebaa-11ea-85f6-7a782c237202.png)

**Comment by njmattes** [comment]
Done(ish).
