### ISSUE TITLE
Map disappears visually if you open and then close modal

### ISSUE THREAD

**Issue by bkleeman** [RDCEP/energy-maps#3]
# Steps to reproduce

1. Load or refresh the landing page. Do not drag the map around.
2. Click the nav link to open the modal. You will see that the map still appears in the background, with a white background filling its containing div. 
3. Click anywhere on the screen besides the modal. You will either see the map's white background disappear or you will see the map disappear behind the grey background entirely. 
    1. If the map is still visible, click somewhere in the background again. You will see the map disappear.
4. Close the modal. You will see that the map does not reappear. However, it still exists in the DOM in its current state. 
5. If you can find the map's location on the page while invisible, drag the map. It should reappear.

# Screenshots

![image](https://user-images.githubusercontent.com/20052075/81965125-3d7af200-95dd-11ea-97c6-bedc2124a1d7.png)
![image](https://user-images.githubusercontent.com/20052075/81965162-48358700-95dd-11ea-9911-afc8001407f3.png)
![image](https://user-images.githubusercontent.com/20052075/81965198-5388b280-95dd-11ea-92b9-081fb9c19cab.png)
![image](https://user-images.githubusercontent.com/20052075/81965221-5aafc080-95dd-11ea-8fee-2967eab01ba1.png)

- Map dragged to demonstrate that the canvas node's state in the DOM is unchanged when hidden like this.

![image](https://user-images.githubusercontent.com/20052075/81965267-6bf8cd00-95dd-11ea-917a-c607049b1f20.png)

# Recommendations

-

**Comment by njmattes** [comment]
This is fixed I think. On the `bucket-o-fish` commit 200428. I'm sure there's a fancy way to link to that in this chat but ¯\_(ツ)_/¯ as they say.
