### ISSUE TITLE
Inconsistent plurals in map options

### ISSUE THREAD

**Issue by njmattes** [RDCEP/energy-maps#35]
Most options are render as singular entities (e.g. 'coal mine', 'natural gas plant'). However the following are plural:

* Wind farms
* AC lines under 100 kV
* AC lines 100–300 kV
* AC lines 345–735 kV
* DC lines
* Foreign oil wells
* Foreign gas wells
* State boundaries

They should be consistent. Suggestion: plural when concrete nouns (e.g. 'gas wells'), singular when abstract (e.g. 'wind capacity' not 'wind capacities').

**Comment by bkleeman** [comment]
Done and pushed to `no-zoom`, still needs to be implemented in `dev`

**Comment by bkleeman** [comment]
Implemented and pushed to `dev`
