### ISSUE TITLE
Move checkbox menu toggle over by the text “map options”

### ISSUE THREAD

**Issue by bkleeman** [RDCEP/energy-maps#39]
We are experiencing some *potential* usability issues in terms of dragging the menu away and it being "hard to get back to" at that point. This is a short term fix. We may, or may not, want to rethink our UI.

**Comment by njmattes** [comment]
This is pretty much redundant with #71. Not exactly, but we'll need new buttons for docking rather than minimizing to the menubar. So I'm closing this.
