### ISSUE TITLE
Put zoom +/- somewhere in one place, independent of the checkbox menu

### ISSUE THREAD

**Issue by bkleeman** [RDCEP/energy-maps#40]

**Comment by njmattes** [comment]
Getting ready to start rolling some code for this. For what it's worth, Google Maps places ± in the bottom right, as does Apple Maps, as does Waze. Bing in the top right, as does Maps.com. Mapquest on the right edge about a third of the way down.

**Comment by njmattes** [comment]
Closing this as it's redundant with #71
