### ISSUE TITLE
Map appears in the wrong spot on load

### ISSUE THREAD

**Issue by bkleeman** [RDCEP/energy-maps#5]
# Description

- Map currently loads in the upper left hand corner of the window:

![image](https://user-images.githubusercontent.com/20052075/81965583-de69ad00-95dd-11ea-826f-581126f35ebd.png)

- Map should appear in the center of the application

![image](https://user-images.githubusercontent.com/20052075/81965613-ea556f00-95dd-11ea-977e-2b83b06b4a65.png)

**Comment by njmattes** [comment]
This is part and parcel of the zoom functionality. The x / y / z translation and scaling of the map need to be codified in the JavaScript. Ie, the map will always be positioned along the x and y axes, and zoomed according to some factor along the z axis (sort of). Now that the `<div>` that holds the map fills the browser, `x` and `y` not only need to be updated when the `zoom` function is triggered, but also on page load and window resize.

On page load, `x` should be equal to the width of the window minus the width of the content area divided by 2. And `y` equal to the height of the header (plus whatever buffer we might want visually). So, pseudo-code...

```
let x = (window.width - d3.select(main).select(content-area).width) / 2;
let y = d3.select(header).height;
```
