### ISSUE TITLE
Reduce words in checkbox menu to allow it to be smaller

### ISSUE THREAD

**Issue by bkleeman** [RDCEP/energy-maps#50]

**Comment by bkleeman** [comment]
Would like review from @njmattes 

I made a branch called `menu-trim` and adjusted the text length and size of both the menu and the legend. 
Also made it so the legend is hidden by default, appears when a user makes a selection, and disappears when there are no active layers. I just find it less irritating than the default loading position but I know it wasn't asked for an I'm not married to it. Easy to undo.

**Comment by njmattes** [comment]
I'm just going through cleaning up tickets. This is old and completed correct?
