### ISSUE TITLE
Stop fullscreen viewing from destroying state boundaries

### ISSUE THREAD

**Issue by bkleeman** [RDCEP/energy-maps#55]
If you enter fullscreen mode in your browser, if state boundaries are active they will disappear. If they are not active, you won't be able to turn them on. If you exit fullscreen mode, you still can't see them. Oddly, this hasn't been observed in Safari yet. Just Chrome and Firefox.

Determine whether this has something to do with fullscreen mode compatibility (is that even a thing?), if it's destroying the canvas node in the DOM, or what is happening. Super weird.

**Comment by bkleeman** [comment]
Preliminary Analysis & Investigation:

Why would entering or exiting full screen mode in a web browser make an HTML5 canvas element visually disappear, without destroying or modifying it in the DOM and without raising any errors when the listener fires?

The `<canvas>` element still exists in the DOM, and the listener `draw_state_boundaries() `still fires and logs the object to the console. Doesn't matter if you press F11 or toggle it in the browser toolbar. If you load the page in standard view, turning on full screen makes the layer disappear. If you load the page in full screen mode, turning off full screen makes the layer disappear.

Is there something unique about the [full screen API ](https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API) that would cause behavior like this? Or that would cause only one single element to just visually disappear?

Default load state, where the layer in question is turned on on load.

![image](https://user-images.githubusercontent.com/20052075/101075383-8f7a6980-3567-11eb-8f5c-29fb57d4f8c4.png)

Immediately after entering full screen mode. DOM node still exists, checkbox is still checked, listener fires again as expected.3

![image](https://user-images.githubusercontent.com/20052075/101075427-9e611c00-3567-11eb-96fe-f6e3363d5bce.png)

Still able to log the canvas object to the console.

![image](https://user-images.githubusercontent.com/20052075/101075455-a91bb100-3567-11eb-9598-334250a2d118.png)

**Comment by njmattes** [comment]
I think this is a bug in Chrome actually. It looks to me like if we change the styling of the state borders so that they're solid and don't use the `ctx.setLineDash()` method, then they render fine (but they're ass ugly). The dashed lines render fine in Safari.

Thanks Google.

**Comment by bkleeman** [comment]
Looks like this issue is happening in both Chrome and Firefox. 
I also just found that opening dev tools (ctrl+shift+i) in both Chrome and Firefox causes the same issue.
In Chrome, same thing happens if you toggle your bookmarks bar (ctrl-shift-b).

I'm wondering if this is just an issue with a variety of less commonly used browser features?

**Comment by njmattes** [comment]
For the time being I made state borders solid grey. I hate it, but I hate so much who cares anymore. Closing this.
