### ISSUE TITLE
Map disappears visually when you click anywhere else on the zoom surface aside from the base map/mapcanvas

### ISSUE THREAD

**Issue by bkleeman** [RDCEP/energy-maps#6]
# Description

- This seems to be the same issue seen in [issue #3](https://github.com/RDCEP/energy-maps/issues/3), but more generalized than previously expected.
- The map seems to disappear any time you click on an area of the zoom surface that does not overlap with `<div class="map layer base-map">` or `<canvas id="mapcanvas" width="1200" height="600" style="transform: translate(3px, 67px) scale(1);"></canvas>`

**Comment by njmattes** [comment]
Which branch is this occurring on? I can't replicate anything like this on the `bucket-o-fish` branch.

**Comment by bkleeman** [comment]
`adapt-to-new-css`
