### ISSUE TITLE
P2: When I click off the map, don't redraw the screen

### ISSUE THREAD

**Issue by bkleeman** [RDCEP/energy-maps#61]

**Comment by njmattes** [comment]
I believe this has to do with debouncing. If I'm not mistaken, map pan/zoom is debounced using the `underscore` library. But it's debounced over time. Given issue #63, it would probably behoove us to work on finding or writing a function to debounce drag events in space.

**Comment by njmattes** [comment]
This has been pushed to [`feature-spatial-debounce`][(https://github.com/RDCEP/energy-maps/tree/feature-spatial-debounce). @bkleeman can you check it and merge if you're cool with it?
