### ISSUE TITLE
P3: When zooming out, shift the image toward the center of the screen. (Zooming in is fine as is, where the mouse spot stays fixed.)

### ISSUE THREAD

**Issue by bkleeman** [RDCEP/energy-maps#66]

**Comment by njmattes** [comment]
I'm confused by this. As far as I'm aware, the zooming either in or out is relative to the mouse. Except when using the +/– buttons (in which case the mouse position is irrelevant to the map).

**Comment by bkleeman** [comment]
Marked with "question" label, we need more info.
