### ISSUE TITLE
The "tip of Texas"

### ISSUE THREAD

**Issue by njmattes** [RDCEP/energy-maps#67]
When the page opens, if the entire map does not fit on the screen, all future renders of the assets layers are clipped to the original screen bounds. (That's a shitty description, but it's what I can muster this morning.)

**Comment by njmattes** [comment]
The issue is that we're calling `ctx.clip(region)` so as not to be drawing e.g. every single oil well on the map when the user is zoomed in to look at a smaller region. The `region` is a `Path2D()` object whose `rect()` method takes x and y translation args and then width and height args. We have been passing `0` for the first two args. Need to pass the negative `transform.x` and `transform.y` values (in the global (ugh) `transform` object)

**Comment by njmattes** [comment]
Fixed in [`fix-map-cut-off`](https://github.com/RDCEP/energy-maps/tree/fix-map-cut-off). @bkleeman I'm assigning to you in case you want to look at the fix before it's merged to `dev`.

**Comment by bkleeman** [comment]
I will check this out!

**Comment by bkleeman** [comment]
I think we can safely merge and deploy everything except for this change. It is introducing more bugs for me now than I've ever seen re: clipping region. Not sure how to describe at this time, sorry! Video chat might help. For now, I am merging the checkbox and typography changes and pushing to `origin/dev`.

**Comment by njmattes** [comment]
Bugs here are fixed and merged. `clearRect()` had not been updated to reference the `transform` object.
