### ISSUE TITLE
P3: When panning, keep the image drawn at a lower resolution rather than erasing and redrawing  - EJM - this seems hard

### ISSUE THREAD

**Issue by bkleeman** [RDCEP/energy-maps#69]

**Comment by njmattes** [comment]
Continually redrawing the map features while zooming is too resource intensive and will degrade performance to a point that's infeasible. This is why [earth.nullschool.net](http://earth.nullschool.net) removes its animation during zoom events. 

Another strategy would be that of [EIA's US Energy Mapping System](https://www.eia.gov/state/maps.php) that uses a sort of tile server. They send queries to an API that responds with static images of the various energy resources which gets layered on top of their map. If memory serves this is all built on top of ESRI components, so probably not a pattern we want to follow. 

Once we build (if we can ever allocate the time to building...) an API for this application, savvier solutions are possible. But for now, this can't/won't be implemented.
