### ISSUE TITLE
Fix layer bug where chunks stop redrawing after pan/zoom

### ISSUE THREAD

**Issue by bkleeman** [RDCEP/energy-maps#73]
## Partial redraw issue on select pan/zoom events
On select pan/zoom events, chunks of the map fail to redraw to strange regions of the map. This happens particularly when the map is partially dragged off screen. Sometimes you will get a giant green block covering part of the screen when something green is drawn, like the wind map or wells.

This issue takes top priority and is our main bottleneck to moving forward with API/backend dev. More description to come.

### Events that cause the issue:

* Zooming out, dragging the map partially off-screen, then zooming in or out and dragging the map fully on screen again before the layers get a chance to redraw in between.
* If the page initially loads with part of the continent off-screen due to global browser zoom level or screen size, once you zoom out, the portion that was off-screen will fail to load the infrastructure data. You can subvert this by reducing browser zoom level so the map loads in the same spot all at once, but that effects the position of the map on load.

![image](https://user-images.githubusercontent.com/20052075/113020734-816cdc00-9148-11eb-9386-dd49a76c3625.png)

https://user-images.githubusercontent.com/20052075/113213790-3d5c0300-923e-11eb-9c42-c3a13fe6f454.mov

### More considerations
Clipping of the Path2D() region object is likely involved somehow for each layer object. Seems like it’s clipping too late. Perhaps it’s not tracking the state of the transform during drag events -- the state of the transform is different when it’s passed to the rect (region) object vs during the drawing portion of all of that. We're tracking `k` now with a boolean value, `k_changed`.

We have tried changing our iteration constructs from `for` loops to `Array.map()` operations, but the jury is out as to whether what we need is speed or synchronicity. `for` loops will improve performance, but `Array.map()` will perform operations synchronously. Either way, since part of the issue is performance, we can decrease latency by continuing to reduce work done per iteration.

#### Async programming, concurrency, etc.
[Making asynchronous programming easier with async and await](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Async_await)
[Using Web Workers](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers)
[Using Promises](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises)
[Asynchronous JavaScript](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous)
[Concurrency model and the event loop](https://developer.mozilla.org/en-US/docs/Web/JavaScript/EventLoop)

#### Canvas
[Drawing shapes with canvas](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Drawing_shapes)
[Compositing and clipping](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Compositing)

**Comment by njmattes** [comment]
Can we detail the events that cause this to happen?

**Comment by bkleeman** [comment]
Yes. Let's add them in comments here as they come up and I will add them to the issue description. Here's one to start:

On MacBook Pro trackpad, if I zoom in, drag the map partially off screen, then zoom out, and drag the map fully on screen again, then sometimes layers won't draw to a portion of the map.

**Comment by bkleeman** [comment]
@njmattes I updated the description with some more detail. Let's make this our main space to describe the issue and whatever hunches we come up with. If you can think of anything else, feel free to comment here or tell me and I'll keep it updated best I can.

**Comment by njmattes** [comment]
I think part of this is speed, but part of it is not. For the part of the issue that is related to speed/asynchronicity, we could disable new zoom events until the current zoo/pan/redraw is completed. 

For the part that is not a problem with speed of execution...

1. Load the page
2. Don't load any layers
2. Zoom in until the map is bigger than your browser (e.g. click on the + ten times or so)
3. Pan the map

The state boundaries in the western US and along the Canadian border do not clear before the redraw begins whilst dragging. The actual amount of boundaries that don't get cleared changes depending on where the center of the map is on screen. And it does not seem to ever be the case that eastern boundaries don't clear while western ones do. 

If you now turn a data layer on, that layer will not render in the west and north where the state boundaries do not clear. 

This behavior seems to be entirely unrelated to execution speed. It fucks up predictably, in the same way each time, no matter how quickly one drags and clicks and fucks about.

**Comment by njmattes** [comment]
Barring the performance-related bugs, I think the other layer rendering issues can be solved by replacing `region.rect(-transform.x, -transform.y, width, height)` with `region.rect(0, 0, width, height)` everywhere in the code. I think it only shows up in a few places.
